import { Business } from '@/types';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export type ScanExportMeta = {
  date: Date;
  lat: number;
  lng: number;
  radiusKm: number;
  place?: string | null;
};

function formatDate(d: Date, lang: 'fr' | 'en') {
  return d.toLocaleDateString(lang === 'fr' ? 'fr-FR' : 'en-US', {
    day: 'numeric', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit',
  });
}

export function exportScanToPdf(businesses: Business[], meta: ScanExportMeta, lang: 'fr' | 'en' = 'fr') {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;

  // Header band
  doc.setFillColor(45, 169, 124); // brand emerald
  doc.rect(0, 0, pageWidth, 64, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text('Devora', margin, 40);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(lang === 'fr' ? 'Rapport de scan — entreprises détectées' : 'Scan report — detected businesses', margin, 55);

  // Meta block
  doc.setTextColor(20, 20, 20);
  let y = 90;
  const metaLines = lang === 'fr'
    ? [
        `Date du scan : ${formatDate(meta.date, lang)}`,
        `Position : ${meta.lat.toFixed(5)}, ${meta.lng.toFixed(5)}${meta.place ? ` (${meta.place})` : ''}`,
        `Rayon / distance scannée : ${meta.radiusKm} km`,
        `Entreprises détectées : ${businesses.length}`,
      ]
    : [
        `Scan date: ${formatDate(meta.date, lang)}`,
        `Position: ${meta.lat.toFixed(5)}, ${meta.lng.toFixed(5)}${meta.place ? ` (${meta.place})` : ''}`,
        `Radius / distance scanned: ${meta.radiusKm} km`,
        `Businesses detected: ${businesses.length}`,
      ];
  doc.setFontSize(10);
  for (const line of metaLines) {
    doc.text(line, margin, y);
    y += 16;
  }

  const head = lang === 'fr'
    ? [['#', 'Nom', 'Catégorie', 'Lieu', 'Téléphone', 'Email', 'Site web']]
    : [['#', 'Name', 'Category', 'Location', 'Phone', 'Email', 'Website']];

  const body = businesses.map((b, i) => [
    String(i + 1),
    b.name,
    b.category || '—',
    [b.district, b.city].filter(Boolean).join(', ') || '—',
    b.phone || '—',
    b.email || '—',
    b.website || (lang === 'fr' ? 'Aucun' : 'None'),
  ]);

  autoTable(doc, {
    startY: y + 10,
    head,
    body,
    styles: { fontSize: 8, cellPadding: 4 },
    headStyles: { fillColor: [45, 169, 124], textColor: 255 },
    alternateRowStyles: { fillColor: [245, 247, 246] },
    margin: { left: margin, right: margin },
    didDrawPage: () => {
      const pageCount = doc.getNumberOfPages();
      const h = doc.internal.pageSize.getHeight();
      doc.setFontSize(8);
      doc.setTextColor(140, 140, 140);
      doc.text(
        lang === 'fr'
          ? `Généré par Devora — devora.app · Page ${doc.getCurrentPageInfo().pageNumber}/${pageCount}`
          : `Generated by Devora — devora.app · Page ${doc.getCurrentPageInfo().pageNumber}/${pageCount}`,
        margin, h - 20
      );
    },
  });

  // Signature / stamp block at the end
  const finalY = (doc as any).lastAutoTable.finalY + 30;
  const stampY = Math.min(finalY, doc.internal.pageSize.getHeight() - 80);
  doc.setDrawColor(45, 169, 124);
  doc.setLineWidth(1);
  doc.roundedRect(pageWidth - margin - 160, stampY, 160, 50, 4, 4);
  doc.setTextColor(45, 169, 124);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('DEVORA', pageWidth - margin - 150, stampY + 20);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(90, 90, 90);
  doc.text(formatDate(new Date(), lang), pageWidth - margin - 150, stampY + 35);

  const fileName = `devora-scan-${meta.date.toISOString().slice(0, 10)}.pdf`;
  doc.save(fileName);
}

export function exportScanToCsv(businesses: Business[], meta: ScanExportMeta, lang: 'fr' | 'en' = 'fr') {
  const headers = lang === 'fr'
    ? ['Nom', 'Catégorie', 'Ville', 'Quartier', 'Téléphone', 'Email', 'Site web', 'A un site', "Score d'opportunité"]
    : ['Name', 'Category', 'City', 'District', 'Phone', 'Email', 'Website', 'Has website', 'Opportunity score'];

  const escape = (v: unknown) => {
    const s = v === null || v === undefined ? '' : String(v);
    return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
  };

  const rows = businesses.map(b => [
    b.name, b.category || '', b.city || '', b.district || '',
    b.phone || '', b.email || '', b.website || '',
    b.hasWebsite ? (lang === 'fr' ? 'Oui' : 'Yes') : (lang === 'fr' ? 'Non' : 'No'),
    b.opportunityScore ?? '',
  ]);

  const metaComment = lang === 'fr'
    ? `# Devora — scan du ${formatDate(meta.date, lang)} — position ${meta.lat.toFixed(5)},${meta.lng.toFixed(5)} — rayon ${meta.radiusKm}km`
    : `# Devora — scan on ${formatDate(meta.date, lang)} — position ${meta.lat.toFixed(5)},${meta.lng.toFixed(5)} — radius ${meta.radiusKm}km`;

  const csv = [metaComment, headers.map(escape).join(','), ...rows.map(r => r.map(escape).join(','))].join('\n');
  const blob = new Blob(['﻿' + csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `devora-scan-${meta.date.toISOString().slice(0, 10)}.csv`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
