project_id = "abifmrsvbhbzhwdubwvu"

[functions.discover-businesses]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.campay-webhook]
verify_jwt = false

[functions.maviance-webhook]
verify_jwt = false

[functions.daily-notifications]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.shared-scan]
verify_jwt = false
